// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV08f4di0NMmF0ckCqI2zpeUzX6YfQF9U',
    appId: '1:817290769095:web:d12b809d2d0888e6d444e2',
    messagingSenderId: '817290769095',
    projectId: 'diabetes-24240',
    authDomain: 'diabetes-24240.firebaseapp.com',
    storageBucket: 'diabetes-24240.firebasestorage.app',
    measurementId: 'G-QXHFENM25S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsqdNDPPLl6q66J-GMDKbhvlbmHewfDoU',
    appId: '1:817290769095:android:d191823d1ebd1048d444e2',
    messagingSenderId: '817290769095',
    projectId: 'diabetes-24240',
    storageBucket: 'diabetes-24240.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9WNqo4Fij_I7jKrOoHfh0nVA6hjdUW9s',
    appId: '1:817290769095:ios:de75875c12cfe770d444e2',
    messagingSenderId: '817290769095',
    projectId: 'diabetes-24240',
    storageBucket: 'diabetes-24240.firebasestorage.app',
    iosBundleId: 'com.example.diabetesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9WNqo4Fij_I7jKrOoHfh0nVA6hjdUW9s',
    appId: '1:817290769095:ios:de75875c12cfe770d444e2',
    messagingSenderId: '817290769095',
    projectId: 'diabetes-24240',
    storageBucket: 'diabetes-24240.firebasestorage.app',
    iosBundleId: 'com.example.diabetesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV08f4di0NMmF0ckCqI2zpeUzX6YfQF9U',
    appId: '1:817290769095:web:72c2996af8efcfddd444e2',
    messagingSenderId: '817290769095',
    projectId: 'diabetes-24240',
    authDomain: 'diabetes-24240.firebaseapp.com',
    storageBucket: 'diabetes-24240.firebasestorage.app',
    measurementId: 'G-6D5TQD0X6H',
  );
}
